API_URL = "https://fatigue-risk-api.onrender.com/predict"

EXEC_PBI_EMBED = "PASTE_EXECUTIVE_POWERBI_EMBED_URL"
CCTV_PBI_EMBED = "PASTE_CCTV_POWERBI_EMBED_URL"
GEOF_PBI_EMBED = "PASTE_GEOFENCE_POWERBI_EMBED_URL"

EXEC_PBI_LINK = "PASTE_EXECUTIVE_REPORT_LINK"
CCTV_PBI_LINK = "PASTE_CCTV_REPORT_LINK"
GEOF_PBI_LINK = "PASTE_GEOFENCE_REPORT_LINK"
